
//! \file   InitGlobalParameters.h
//! \brief  Initialization of the global parameters.
//__________________________________________________________________________________________________

#import <UIKit/UIKit.h>

#import "GlobalParameters.h"
//__________________________________________________________________________________________________

@class AppViewController;
//__________________________________________________________________________________________________

GlobalParameters* InitGlobalParameters(AppViewController* viewController);
//__________________________________________________________________________________________________
